---
name: Semantic Release

on:
  workflow_dispatch:
    inputs:
      force-deployment:
        description: >-
          Version component to force, or auto to use semantic commit parsing.
        required: false
        type: choice
        default: auto
        options:
          - auto
          - prerelease
          - patch
          - minor
          - major

permissions:
  contents: write

concurrency:
  group: semantic-release
  cancel-in-progress: false

jobs:
  release:
    if: >-
      github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
    name: Release
    # yamllint disable-line rule:line-length
    uses: worganisation/github-config-files/.github/workflows/__semantic-release.yml@ee8b4dc6cf460b098e4da3af614df6694818e8c0
    with:
      python-version: '3.14'
      force-deployment: >-
        ${{ inputs.force-deployment != 'auto' && inputs.force-deployment || '' }}
      runner-labels: '"ubuntu-latest"'
      semantic-release-version: 10.6.2
    secrets: inherit
